# .github/workflows/hello.yml
on: push # runs when ever there is a push to any branch of the repo
name: A workflow for my Hello World Action
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest # useful environment so we can run a simple bash
    steps:
    - name: Say hello!
      run: |
        echo "hello $NAME"
      env:
        NAME: Chris
    - name: Say hello to the actor!
      run: |
        echo "hello $GITHUB_ACTOR"


  debug:
    name: Debug all the contexts
    runs-on: ubuntu-latest
    steps:
    - name: debug checks
      run: |
        echo "ENV:"
        env
        echo " github context - ${{toJson(github) }}"
        echo " job context - ${{toJson(job) }}"
        echo " steps context - ${{toJson(steps) }}"
        echo " secrets context - ${{toJson(secrets) }}"
        echo " strategy context - ${{toJson(strategy) }}"
        echo " matrix context - ${{toJson(matrix) }}"
